FROM volcengine/sandbox-fusion:server-20241204

RUN mkdir -p /var/run/sshd
RUN apt-get update
RUN apt-get update --fix-missing && apt-get install -y wget g++ git make libdpkg-perl sudo vim unzip unrar openssh-server openssh-client ca-certificates psmisc screen --no-install-recommends
RUN rustup default stable 
RUN apt-get install -y nginx
RUN apt-get install -y python3-pip
RUN python3 -m pip install supervisor
RUN rm -rf /root/sandbox
WORKDIR /root